---
#- name: apply some rogue changes using ansible
- hosts: eosnodes
  gather_facts: False
  connection: local
  tasks:
  - name: add some vlans
    eos_vlan:
      authorize: yes
      aggregate:
        - vlan_id: 3000
        - {vlan_id: 3002, name: vlan-3002}
        - {vlan_id: 3003, name: vlan-3003}
        - {vlan_id: 4000, name: vlan-4000}
        - {vlan_id: 4001, name: vlan-4001}
        - {vlan_id: 4002, name: vlan-4002}
        - {vlan_id: 4003, name: vlan-4003}
        - {vlan_id: 4004, name: vlan-4004}
        - {vlan_id: 4005, name: vlan-4005}

  - name: configure the login banner
    eos_banner:
      authorize: yes
      banner: login
      text: |
        THIS IS THE NEW BANNER
        PLACED HERE BY ROGUE
        ANSIBLE USER
      state: present