---
- name: apply common configuration to all nodes
#- hosts: rpi3-5.lan
  hosts: cluster01
  remote_user: root
  roles: 
  - bennojoy.ntp
  tasks:
    - name: Update apt-cache
      apt: update_cache=yes

    - name: Install nginx  
      apt: name=nginx state=latest
      notify:
      - start nginx

#    - name: uninstall ntopng
#      apt: name=ntopng state=removed

#    - name: uninstall ntopng-data
#      apt: name=ntopng-data state=removed

    - name: Install ntopng
      apt: name=ntopng state=latest
      notify:
      - start ntopng

    - name: Install dnsutils
      apt: name=dnsutils state=latest
      tags:
      - packages

    - name: Install git
      apt: name=git state=latest
      tags:
      - packages

    - name: Install lldpdad
      apt: name=lldpad state=latest
      notify:
      - start lldpad
      tags:
      - packages

    - name: Remove Wolfram packages
      apt: name=wolfram-engine state=absent
      tags:
      - packages

    - name: Remove Wolfram packages
      apt: name=wolframscript state=absent
      tags:
      - packages

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: "FIX: Ansible autoremove doesn't work, falling back to shell"
      shell: apt-get autoremove -y
      become: 'true'

    - name: Transfer the config-lldp script
      script: /etc/ansible/scripts/config-lldp 
      tags:
      - packages

    - name: Transfer the getlldp script
      script: /etc/ansible/scripts/getlldp 
      tags:
      - packages

  handlers:
    - name: start nginx
      service: name=nginx state=started

    - name: start ntopng
      service: name=ntopng state=started

    - name: start lldpad
      service: name=lldpad state=started

